# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM node:lts-alpine

WORKDIR /app

# Copy package files and install dependencies
COPY package*.json ./

# Install dependencies without running prepare scripts
RUN npm install --ignore-scripts

# Copy the rest of the application
COPY . .

# Build the project
RUN npm run build

# Ensure the entrypoint has execution permissions
RUN chmod +x build/index.js

# Expose port if needed (not specified, using stdio so not necessary)

CMD ["node", "build/index.js"]
